[workspace]
members = [
    ".",
    "comtains_macros",
]

[package]
name = "comtains"
version = "0.1.1"
edition = "2024"
authors = ["Leander Kohler"]
description = "Zero-allocation byte-set matcher generated at compile time"
license = "MIT"
repository = "https://github.com/Coffeeri/comtains"
documentation = "https://docs.rs/comtains"
homepage = "https://github.com/Coffeeri/comtains"
readme = "README.md"
keywords = ["compile-time", "proc-macro", "trie", "byte", "matcher"]
categories = ["development-tools::profiling", "algorithms", "no-std"]

[dependencies]
comtains_macros = { path = "comtains_macros", version = "0.1.0" }

[dev-dependencies]
iai-callgrind = "0.16"
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
tango-bench = "0.6"

[[bench]]
name = "byte_set"
harness = false

[[bench]]
name = "byte_set_tango"
harness = false
