[workspace]
members = [
    ".",
    "comtains_macros",
]

[package]
name = "comtains"
version = "0.1.0"
edition = "2024"

[features]
default = []
debug-metadata = []

[dependencies]
comtains_macros = { path = "comtains_macros" }

[dev-dependencies]
iai-callgrind = "0.15"
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }

[[bench]]
name = "byte_set"
harness = false
